POST http://localhost:5000/api/places
Content-Type: application/json

{
  "title": "New York Stock Exchange",
  "description": "Where the money lives.",
  "creator": "u2",
  "address": "11 Wall st, New York, NY 10005",
  "coordinates": {
    "lat": 40.706877,
    "lng": -74.0134541
  }
}