### Create Place
POST http://localhost:5000/api/places
Content-Type: application/json

{
  "title": "Empire State Building",
  "description": "A very famous building in New York",
  "address": "20 W 34th St, New York, NY 10001",
  "creator": "u2"
}

### 

GET http://localhost:5000/api/places/user/u2

###

GET http://localhost:5000/api/places/p1

###

PATCH http://localhost:5000/api/places/p1
Content-Type: application/json

{
  "title": "Empire State of Mind",
  "description": "A pretty catchy song"
} 

###

DELETE http://localhost:5000/api/places/p1

###

GET http://localhost:5000/api/000000