### Create Place
POST http://localhost:5000/api/places
Content-Type: application/json

{
  "title": "Empire State Building",
  "description": "A very famous building in New York",
  "address": "20 W 34th St, New York, NY 10001",
  "creator": "u2"
}

### GET PLACE BY ID
GET http://localhost:5000/api/places/63e00b50198ea02d2ae86596

### GET PLACE BY USER ID
GET http://localhost:5000/api/places/user/u2

### UPDATE PLACE BY ID
PATCH http://localhost:5000/api/places/63e00b50198ea02d2ae86596
Content-Type: application/json

{
  "title": "The Empire State Building",
  "description": "A great building in NYC"
} 

### DELETE PLACE BY ID
DELETE http://localhost:5000/api/places/p1