### GET USERS
GET http://localhost:5000/api/users

### SIGNUP
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@test.com",
  "password": "coolPassword",
}

### LOGIN
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "coolPassword"
}