GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "test@test.com",
  "password": "testing",
  "places": "p1"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "testing"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "wrongpassword"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "wrong@email.com",
  "password": "testing"
}